name: NBTFixer
version: ${project.version}
main: com.yiorno.nbtfixer.NBTFixer
api-version: 1.17
authors: [ yossy_zip ]
commands:
  mythicnbttest:
    description: aaa
  nbt:
    description: show nbt
  replacecointest:
    description: bbb